migration: Generate certificates before starting httpd (RBL-7943)

diff --git a/scripts/group-script b/scripts/group-script
--- a/scripts/group-script
+++ b/scripts/group-script
@@ -126,10 +126,19 @@ if [ `uname -m` = "x86_64" ]; then
     rm -rf /usr/lib/raa/rPath/
 fi
 
-# Start apache, if not chrooted
+# Generate rMake certificates IFF we're not chrooted; otherwise we
+# might end up sticking them pre-generated in the ISOs which would be
+# very bad.
+#   -- 5.0.0 - 2008-12-01
 if [ "x$is_chrooted" == "x" ]
 then
+    "$scriptdir"/generate-certs.sh \
+        || die "Failed to generate certificates"
+
+    # Start apache with new certificates.
     service httpd start
+else
+    echo Skipping certificate generation due to chrooting
 fi
 
 # If rmake repo didn't exist, this must be a new install, so only touch the
@@ -158,18 +167,6 @@ do
     fi
 done
 
-
-# Generate rMake certificates IFF we're not chrooted; otherwise we
-# might end up sticking them pre-generated in the ISOs which would be
-# very bad.
-#   -- 5.0.0 - 2008-12-01
-if [ "x$is_chrooted" == "x" ]
-then
-    "$scriptdir"/generate-certs.sh \
-        || die "Failed to generate certificates"
-else
-    echo Skipping certificate generation due to chrooting
-fi
 
 # Restart rMake after update + cert generation. This also straightens things out
 # for the first update after the messagebus was split.
